global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "witch-otel-self-metrics"
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: "witch-otel-metrics"
    static_configs:
      - targets: ["otel-collector:9090"]

  - job_name: "witch-tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "witch-loki"
    static_configs:
      - targets: ["loki:3100"]
