publish {
  maxPastTime = "5 minutes"
}

jwt {
  secret = "12345678"
}

postgres {
  connectionString = "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
}

storage {
  type = "local"

  local {
    path = "/tmp/witch-please"
  }
}
