name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: ./witch-please
    
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_BOT_SECRET: ${{ secrets.TELEGRAM_BOT_SECRET }}
      USER_SECRET_PEPPER: ${{ secrets.USER_SECRET_PEPPER }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Set up sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt   

      - name: Cache Scala build
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: scala-cache-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            scala-cache-${{ runner.os }}
            
      - name: Debug USER_SECRET_PEPPER
        run: |
          if [ -z "${USER_SECRET_PEPPER}" ]; then
            echo "USER_SECRET_PEPPER is NOT set"
          else
            echo "USER_SECRET_PEPPER length: ${#USER_SECRET_PEPPER}"
            echo "USER_SECRET_PEPPER starts with: ${USER_SECRET_PEPPER:0:5}..."
          fi
          
      - name: Run tests
        run: sbt test